// ──────────────────────────────────────────────────────────────────────────────
// ExamGuard incident reports (client-side, jsPDF).
//
//  - generateIncidentPDF(record): one student — cover, incident summary table,
//    full timestamped timeline, and a trust-score line graph over the exam.
//  - generateClassPDF(records): all students on one page, sorted by trust
//    score ascending (most-at-risk first).
//
// The trust graph is drawn with native jsPDF primitives (no chart.js canvas
// capture) so it embeds reliably in every browser.
// ──────────────────────────────────────────────────────────────────────────────

import {
  type ViolationType,
  DEDUCTIONS,
  VIOLATION_LABELS,
  statusFromScore,
  STATUS_META,
} from "@/lib/trustScore"

export interface TimelineEntry {
  type: ViolationType
  label: string
  ts: number          // epoch seconds
}

export interface ScorePoint {
  ts: number          // epoch seconds
  score: number
}

export interface StudentRecord {
  studentId: string
  studentName: string
  examName: string
  score: number
  terminated: boolean
  flagged: boolean
  counts: Record<ViolationType, number>
  timeline: TimelineEntry[]
  history: ScorePoint[]
}

// ── Dark palette (matches the app) ────────────────────────────────────────────

const C = {
  bg:      [13, 17, 23]  as [number, number, number],
  surface: [17, 17, 24]  as [number, number, number],
  border:  [30, 30, 46]  as [number, number, number],
  cyan:    [0, 188, 212]  as [number, number, number],
  white:   [226, 232, 240] as [number, number, number],
  muted:   [100, 116, 139] as [number, number, number],
  green:   [0, 255, 136]  as [number, number, number],
  red:     [255, 51, 102] as [number, number, number],
  yellow:  [250, 204, 21] as [number, number, number],
}

const PAGE_W = 210
const PAGE_H = 297
const MX = 18
const CW = PAGE_W - MX * 2

type Doc = import("jspdf").jsPDF

function fill(doc: Doc) {
  doc.setFillColor(...C.bg)
  doc.rect(0, 0, PAGE_W, PAGE_H, "F")
}

function scoreColor(score: number): [number, number, number] {
  if (score >= 80) return C.green
  if (score >= 60) return C.yellow
  return C.red
}

function fmtTime(ts: number): string {
  return new Date(ts * 1000).toLocaleTimeString("en-IN", { hour12: false })
}

function header(doc: Doc, title: string, subtitle: string) {
  fill(doc)
  doc.setFillColor(...C.cyan)
  doc.rect(0, 0, 3, PAGE_H, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(20)
  doc.setTextColor(...C.white)
  doc.text("ExamGuard", MX, 22)
  doc.setFontSize(11)
  doc.setTextColor(...C.cyan)
  doc.text(title, MX, 30)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(...C.muted)
  doc.text(subtitle, MX, 36)
  doc.setDrawColor(...C.cyan)
  doc.setLineWidth(0.3)
  doc.line(MX, 40, PAGE_W - MX, 40)
}

function footer(doc: Doc, page: number) {
  doc.setFontSize(7)
  doc.setTextColor(...C.muted)
  doc.text("Generated by ExamGuard · Confidential", MX, PAGE_H - 10)
  doc.text(`Page ${page}`, PAGE_W - MX - doc.getTextWidth(`Page ${page}`), PAGE_H - 10)
}

// ── Trust-score line graph (native primitives) ────────────────────────────────

function drawTrustGraph(doc: Doc, history: ScorePoint[], x: number, y: number, w: number, h: number) {
  // Frame
  doc.setFillColor(...C.surface)
  doc.roundedRect(x, y, w, h, 2, 2, "F")
  doc.setDrawColor(...C.border)
  doc.setLineWidth(0.2)
  doc.roundedRect(x, y, w, h, 2, 2, "S")

  const padL = 10, padR = 6, padT = 6, padB = 8
  const gx = x + padL, gy = y + padT
  const gw = w - padL - padR, gh = h - padT - padB

  // Y gridlines at 0/20/40/60/80/100
  doc.setFontSize(6)
  for (let v = 0; v <= 100; v += 20) {
    const yy = gy + gh * (1 - v / 100)
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(gx, yy, gx + gw, yy)
    doc.setTextColor(...C.muted)
    doc.text(String(v), x + 2, yy + 1.5)
  }

  if (history.length === 0) {
    doc.setTextColor(...C.muted)
    doc.setFontSize(8)
    doc.text("No score history recorded.", gx + 4, gy + gh / 2)
    return
  }

  const t0 = history[0].ts
  const t1 = Math.max(history[history.length - 1].ts, t0 + 1)
  const sx = (ts: number) => gx + gw * ((ts - t0) / (t1 - t0))
  const sy = (sc: number) => gy + gh * (1 - sc / 100)

  // Threshold lines (warn=60, terminate=20)
  for (const [val, col] of [[60, C.yellow], [20, C.red]] as const) {
    const yy = sy(val)
    doc.setDrawColor(col[0], col[1], col[2])
    doc.setLineWidth(0.15)
    for (let lx = gx; lx < gx + gw; lx += 4) doc.line(lx, yy, lx + 2, yy) // dashed
  }

  // Score polyline
  doc.setDrawColor(...C.cyan)
  doc.setLineWidth(0.6)
  for (let i = 1; i < history.length; i++) {
    doc.line(sx(history[i - 1].ts), sy(history[i - 1].score), sx(history[i].ts), sy(history[i].score))
  }
  // Endpoint dot
  const last = history[history.length - 1]
  const lc = scoreColor(last.score)
  doc.setFillColor(lc[0], lc[1], lc[2])
  doc.circle(sx(last.ts), sy(last.score), 1.2, "F")
}

// ── Incident summary table ────────────────────────────────────────────────────

function drawSummaryTable(doc: Doc, counts: Record<ViolationType, number>, x: number, y: number): number {
  const types = Object.keys(DEDUCTIONS) as ViolationType[]
  const rowH = 8
  const c1 = x, c2 = x + CW * 0.55, c3 = x + CW * 0.78

  // Header row
  doc.setFillColor(...C.surface)
  doc.rect(x, y, CW, rowH, "F")
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...C.muted)
  doc.text("VIOLATION", c1 + 3, y + 5.5)
  doc.text("COUNT", c2, y + 5.5)
  doc.text("POINTS LOST", c3, y + 5.5)
  let yy = y + rowH

  doc.setFont("helvetica", "normal")
  let totalLost = 0
  for (const t of types) {
    const n = counts[t] ?? 0
    const lost = n * DEDUCTIONS[t]
    totalLost += lost
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(x, yy, x + CW, yy)
    doc.setFontSize(9)
    doc.setTextColor(...(n > 0 ? C.white : C.muted))
    doc.text(VIOLATION_LABELS[t], c1 + 3, yy + 5.5)
    doc.setTextColor(...(n > 0 ? C.yellow : C.muted))
    doc.text(String(n), c2, yy + 5.5)
    doc.setTextColor(...(lost > 0 ? C.red : C.muted))
    doc.text(lost > 0 ? `-${lost}` : "0", c3, yy + 5.5)
    yy += rowH
  }

  // Total row
  doc.setDrawColor(...C.cyan)
  doc.setLineWidth(0.3)
  doc.line(x, yy, x + CW, yy)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(...C.white)
  doc.text("Total deductions", c1 + 3, yy + 6)
  doc.setTextColor(...C.red)
  doc.text(`-${totalLost}`, c3, yy + 6)
  return yy + rowH + 2
}

// ── Public: single-student incident report ────────────────────────────────────

export async function generateIncidentPDF(record: StudentRecord): Promise<void> {
  const { jsPDF } = await import("jspdf")
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true })
  const date = new Date().toISOString().slice(0, 10)

  // ── Page 1: cover + summary + graph ──
  header(doc, "Incident Report", `${record.examName} · ${date}`)

  let y = 50
  // Identity block
  doc.setFontSize(9)
  const idRows: [string, string][] = [
    ["Student", record.studentName || "—"],
    ["Student ID", record.studentId],
    ["Exam", record.examName || "—"],
    ["Date", new Date().toUTCString()],
  ]
  for (const [k, v] of idRows) {
    doc.setFont("helvetica", "bold"); doc.setTextColor(...C.muted)
    doc.text(k.toUpperCase(), MX, y)
    doc.setFont("helvetica", "normal"); doc.setTextColor(...C.white)
    doc.text(v, MX + 32, y)
    y += 6
  }

  // Final score badge
  y += 4
  const sc = scoreColor(record.score)
  doc.setFillColor(sc[0], sc[1], sc[2])
  doc.circle(MX + 14, y + 8, 13, "F")
  doc.setFont("helvetica", "bold"); doc.setFontSize(16); doc.setTextColor(...C.bg)
  const s = String(record.score)
  doc.text(s, MX + 14 - doc.getTextWidth(s) / 2, y + 10)
  doc.setFontSize(13); doc.setTextColor(sc[0], sc[1], sc[2])
  const status = statusFromScore(record.score, record.terminated)
  doc.text(`${STATUS_META[status].label.toUpperCase()}  ·  ${record.score}/100`, MX + 34, y + 6)
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(...C.muted)
  const tags = [
    record.terminated ? "AUTO-TERMINATED" : null,
    record.flagged ? "FLAGGED FOR REVIEW" : null,
  ].filter(Boolean).join("   ·   ")
  if (tags) doc.text(tags, MX + 34, y + 12)
  y += 30

  // Summary table
  doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...C.muted)
  doc.text("INCIDENT SUMMARY", MX, y); y += 4
  y = drawSummaryTable(doc, record.counts, MX, y)

  // Trust graph
  y += 6
  doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...C.muted)
  doc.text("TRUST SCORE OVER TIME", MX, y); y += 4
  drawTrustGraph(doc, record.history, MX, y, CW, 50)
  footer(doc, 1)

  // ── Page 2+: full timeline ──
  doc.addPage(); fill(doc)
  doc.setFillColor(...C.cyan); doc.rect(0, 0, 3, PAGE_H, "F")
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...C.cyan)
  doc.text("Event Timeline", MX, 22)
  doc.setDrawColor(...C.cyan); doc.setLineWidth(0.3); doc.line(MX, 26, PAGE_W - MX, 26)
  let ty = 34
  let page = 2

  if (record.timeline.length === 0) {
    doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...C.muted)
    doc.text("No violations recorded — clean session.", MX, ty)
  } else {
    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5)
    for (const e of record.timeline) {
      if (ty > PAGE_H - 18) {
        footer(doc, page); page++; doc.addPage(); fill(doc)
        doc.setFillColor(...C.cyan); doc.rect(0, 0, 3, PAGE_H, "F"); ty = 22
      }
      doc.setTextColor(...C.muted)
      doc.text(fmtTime(e.ts), MX, ty)
      doc.setTextColor(...C.red)
      doc.text("●", MX + 24, ty)
      doc.setTextColor(...C.white)
      doc.text(e.label, MX + 30, ty)
      doc.setTextColor(...C.muted)
      doc.text(`-${DEDUCTIONS[e.type]}`, PAGE_W - MX - 8, ty)
      ty += 6.5
    }
  }
  footer(doc, page)

  download(doc, `examguard-incident-${slug(record.studentName || record.studentId)}-${date}.pdf`)
}

// ── Public: class summary (one page, all students) ────────────────────────────

export async function generateClassPDF(records: StudentRecord[]): Promise<void> {
  const { jsPDF } = await import("jspdf")
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true })
  const date = new Date().toISOString().slice(0, 10)

  header(doc, "Class Summary", `${records.length} students · ${date}`)

  const sorted = [...records].sort((a, b) => a.score - b.score)  // most-at-risk first

  let y = 48
  const rowH = 9
  // Column header
  doc.setFillColor(...C.surface); doc.rect(MX, y, CW, rowH, "F")
  doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...C.muted)
  doc.text("STUDENT", MX + 3, y + 6)
  doc.text("SCORE", MX + CW * 0.52, y + 6)
  doc.text("STATUS", MX + CW * 0.66, y + 6)
  doc.text("FLAGS", MX + CW * 0.86, y + 6)
  y += rowH

  doc.setFont("helvetica", "normal")
  for (const r of sorted) {
    if (y > PAGE_H - 18) break  // one-page summary per spec
    const sc = scoreColor(r.score)
    const status = statusFromScore(r.score, r.terminated)
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1); doc.line(MX, y, MX + CW, y)
    doc.setFontSize(9); doc.setTextColor(...C.white)
    doc.text(`${r.studentName || r.studentId}`, MX + 3, y + 6)
    doc.setTextColor(sc[0], sc[1], sc[2])
    doc.text(`${r.score}`, MX + CW * 0.52, y + 6)
    doc.setTextColor(...C.muted)
    doc.text(STATUS_META[status].label, MX + CW * 0.66, y + 6)
    const flags = (r.flagged ? "REVIEW " : "") + (r.terminated ? "TERMINATED" : "")
    if (flags.trim()) { doc.setTextColor(...C.red); doc.text(flags.trim(), MX + CW * 0.86, y + 6) }
    y += rowH
  }
  footer(doc, 1)
  download(doc, `examguard-class-summary-${date}.pdf`)
}

// ── helpers ───────────────────────────────────────────────────────────────────

function slug(s: string): string {
  return s.replace(/[^a-zA-Z0-9]/g, "-").replace(/-+/g, "-").slice(0, 30) || "student"
}

function download(doc: Doc, filename: string) {
  const blob = doc.output("blob") as Blob
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
