export interface MCQ {
  id:      string
  text:    string
  options: [string, string, string, string]
  correct: number  // index 0-3
}

export interface SubjectBank {
  id:        string
  label:     string
  icon:      string
  color:     string
  questions: MCQ[]
}

export const QUESTION_BANK: SubjectBank[] = [
  {
    id: "dsa", label: "Data Structures & Algorithms", icon: "🧩", color: "indigo",
    questions: [
      { id: "dsa1",  text: "What is the time complexity of accessing an element in an array by index?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correct: 0 },
      { id: "dsa2",  text: "Which data structure follows the LIFO (Last In First Out) principle?", options: ["Stack", "Queue", "Linked List", "Deque"], correct: 0 },
      { id: "dsa3",  text: "What is the worst-case time complexity of QuickSort?", options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], correct: 0 },
      { id: "dsa4",  text: "In a Binary Search Tree (BST), which traversal gives nodes in sorted order?", options: ["In-order", "Pre-order", "Post-order", "Level-order"], correct: 0 },
      { id: "dsa5",  text: "What is the space complexity of Merge Sort?", options: ["O(n)", "O(1)", "O(log n)", "O(n²)"], correct: 0 },
      { id: "dsa6",  text: "Which algorithm is used to find the shortest path in an unweighted graph?", options: ["BFS", "DFS", "Dijkstra", "Bellman-Ford"], correct: 0 },
      { id: "dsa7",  text: "What data structure is used internally to implement a priority queue?", options: ["Heap", "Stack", "Array", "Linked List"], correct: 0 },
      { id: "dsa8",  text: "What is the time complexity of binary search on a sorted array of n elements?", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], correct: 0 },
      { id: "dsa9",  text: "Which of the following sorting algorithms is stable?", options: ["Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort"], correct: 0 },
      { id: "dsa10", text: "What is the maximum number of nodes at depth d in a binary tree?", options: ["2^d", "2d", "d²", "2^(d-1)"], correct: 0 },
    ],
  },
  {
    id: "cybersecurity", label: "Cybersecurity", icon: "🔐", color: "red",
    questions: [
      { id: "cs1",  text: "What does CIA stand for in the CIA Triad of information security?", options: ["Confidentiality, Integrity, Availability", "Control, Integrity, Access", "Confidentiality, Identity, Authorization", "Control, Information, Availability"], correct: 0 },
      { id: "cs2",  text: "Which attack involves injecting malicious SQL code into an input field?", options: ["SQL Injection", "XSS", "CSRF", "Buffer Overflow"], correct: 0 },
      { id: "cs3",  text: "What encryption algorithm uses a pair of public and private keys?", options: ["RSA", "AES", "DES", "MD5"], correct: 0 },
      { id: "cs4",  text: "Which type of XSS attack stores the malicious script on the server?", options: ["Stored XSS", "Reflected XSS", "DOM-based XSS", "Blind XSS"], correct: 0 },
      { id: "cs5",  text: "What is a Man-in-the-Middle (MITM) attack?", options: ["Intercepting communication between two parties", "Overloading a server with requests", "Guessing passwords by brute force", "Injecting code into a database"], correct: 0 },
      { id: "cs6",  text: "Which protocol provides secure communication over the internet using encryption?", options: ["HTTPS", "HTTP", "FTP", "SMTP"], correct: 0 },
      { id: "cs7",  text: "What is a firewall primarily used for?", options: ["Filtering network traffic based on rules", "Encrypting data at rest", "Detecting viruses in files", "Storing user credentials securely"], correct: 0 },
      { id: "cs8",  text: "What does a digital certificate primarily verify?", options: ["The identity of a public key's owner", "The strength of an encryption algorithm", "The integrity of stored files", "The speed of data transmission"], correct: 0 },
      { id: "cs9",  text: "Which attack floods a server with traffic to make it unavailable?", options: ["DDoS", "Phishing", "Spoofing", "Keylogging"], correct: 0 },
      { id: "cs10", text: "What is the purpose of a hash function in security?", options: ["Producing a fixed-size digest of data", "Encrypting data with a key", "Authenticating users", "Filtering malicious packets"], correct: 0 },
    ],
  },
  {
    id: "aiml", label: "Artificial Intelligence & ML", icon: "🤖", color: "violet",
    questions: [
      { id: "ai1",  text: "Which type of machine learning uses labelled training data?", options: ["Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Semi-supervised Learning"], correct: 0 },
      { id: "ai2",  text: "What does overfitting mean in machine learning?", options: ["Model performs well on training data but poorly on new data", "Model performs poorly on both training and test data", "Model has too few parameters", "Model trains too slowly"], correct: 0 },
      { id: "ai3",  text: "Which activation function outputs values between 0 and 1?", options: ["Sigmoid", "ReLU", "Tanh", "Softmax"], correct: 0 },
      { id: "ai4",  text: "What is the purpose of the learning rate in gradient descent?", options: ["Controls the size of parameter update steps", "Determines the number of training epochs", "Sets the number of layers in the network", "Defines the batch size"], correct: 0 },
      { id: "ai5",  text: "Which algorithm is used for dimensionality reduction by finding principal components?", options: ["PCA", "K-Means", "SVM", "Random Forest"], correct: 0 },
      { id: "ai6",  text: "In a confusion matrix, what does a True Positive represent?", options: ["Correctly predicted positive class", "Incorrectly predicted positive class", "Correctly predicted negative class", "Incorrectly predicted negative class"], correct: 0 },
      { id: "ai7",  text: "What is the vanishing gradient problem in deep learning?", options: ["Gradients become very small, slowing learning in early layers", "Gradients become very large, causing instability", "The model forgets earlier training data", "Loss function stops decreasing"], correct: 0 },
      { id: "ai8",  text: "Which ensemble method builds trees sequentially, each correcting the previous?", options: ["Gradient Boosting", "Random Forest", "Bagging", "Voting Classifier"], correct: 0 },
      { id: "ai9",  text: "What does the term 'epoch' mean in neural network training?", options: ["One complete pass through the entire training dataset", "One update of a single weight", "One forward pass through the network", "One batch of training samples"], correct: 0 },
      { id: "ai10", text: "Which distance metric is used in the K-Nearest Neighbours algorithm by default?", options: ["Euclidean distance", "Manhattan distance", "Cosine similarity", "Hamming distance"], correct: 0 },
    ],
  },
  {
    id: "dbms", label: "Database Management Systems", icon: "🗄️", color: "amber",
    questions: [
      { id: "db1",  text: "Which SQL clause is used to filter records after grouping?", options: ["HAVING", "WHERE", "GROUP BY", "ORDER BY"], correct: 0 },
      { id: "db2",  text: "What does ACID stand for in database transactions?", options: ["Atomicity, Consistency, Isolation, Durability", "Access, Control, Identity, Data", "Atomicity, Concurrency, Integrity, Durability", "Availability, Consistency, Isolation, Durability"], correct: 0 },
      { id: "db3",  text: "Which normal form eliminates partial dependencies?", options: ["2NF", "1NF", "3NF", "BCNF"], correct: 0 },
      { id: "db4",  text: "What type of JOIN returns all rows from both tables, with NULLs where there is no match?", options: ["FULL OUTER JOIN", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN"], correct: 0 },
      { id: "db5",  text: "What is a foreign key?", options: ["A column referencing the primary key of another table", "A unique identifier for a table row", "An index on a frequently queried column", "A constraint preventing NULL values"], correct: 0 },
      { id: "db6",  text: "Which indexing structure is most commonly used in relational databases?", options: ["B-Tree", "Hash Table", "AVL Tree", "Skip List"], correct: 0 },
      { id: "db7",  text: "What does the term 'deadlock' mean in a database context?", options: ["Two transactions waiting on each other indefinitely", "A query that runs infinitely without result", "A table locked by the administrator", "A failed transaction that cannot be rolled back"], correct: 0 },
      { id: "db8",  text: "Which NoSQL database type stores data as key-value pairs?", options: ["Redis", "MongoDB", "Cassandra", "Neo4j"], correct: 0 },
      { id: "db9",  text: "What is the purpose of the ROLLBACK statement?", options: ["Undo all changes made in the current transaction", "Save changes permanently to the database", "Delete all rows from a table", "Revert the database schema to a previous version"], correct: 0 },
      { id: "db10", text: "Which SQL command removes a table and all its data permanently?", options: ["DROP TABLE", "DELETE TABLE", "TRUNCATE TABLE", "REMOVE TABLE"], correct: 0 },
    ],
  },
  {
    id: "os", label: "Operating Systems", icon: "💻", color: "cyan",
    questions: [
      { id: "os1",  text: "What is the main difference between a process and a thread?", options: ["Threads share memory within a process; processes have separate memory", "Processes are faster than threads", "Threads cannot run concurrently", "Processes share the same memory space"], correct: 0 },
      { id: "os2",  text: "Which CPU scheduling algorithm can cause starvation?", options: ["Priority Scheduling", "Round Robin", "FCFS", "Multilevel Queue"], correct: 0 },
      { id: "os3",  text: "What is a page fault?", options: ["A required page is not in physical memory and must be loaded from disk", "An attempt to access an invalid memory address", "A hardware error in the memory module", "An overflow of the page table"], correct: 0 },
      { id: "os4",  text: "Which of the following is NOT one of the four Coffman conditions for deadlock?", options: ["Preemption available", "Mutual exclusion", "Hold and wait", "Circular wait"], correct: 0 },
      { id: "os5",  text: "What does a semaphore do?", options: ["Controls access to a shared resource using a counter", "Allocates memory to a process", "Schedules processes on the CPU", "Manages file system access"], correct: 0 },
      { id: "os6",  text: "Which page replacement algorithm replaces the page that will not be used for the longest time?", options: ["Optimal (OPT)", "LRU", "FIFO", "Clock"], correct: 0 },
      { id: "os7",  text: "What is thrashing in an operating system?", options: ["Excessive paging activity degrading system performance", "A CPU overheating due to high load", "A process consuming 100% CPU", "Memory fragmentation causing slow allocation"], correct: 0 },
      { id: "os8",  text: "In which scheduling algorithm does each process get a fixed time slice?", options: ["Round Robin", "FCFS", "SJF", "Priority Scheduling"], correct: 0 },
      { id: "os9",  text: "What is the role of the Translation Lookaside Buffer (TLB)?", options: ["Cache recent virtual-to-physical address translations", "Store recently used disk blocks in memory", "Speed up context switching", "Buffer I/O operations"], correct: 0 },
      { id: "os10", text: "Which type of kernel runs all OS services in kernel space?", options: ["Monolithic Kernel", "Microkernel", "Hybrid Kernel", "Exokernel"], correct: 0 },
    ],
  },
  {
    id: "cn", label: "Computer Networks", icon: "🌐", color: "teal",
    questions: [
      { id: "cn1",  text: "How many layers are in the OSI model?", options: ["7", "4", "5", "6"], correct: 0 },
      { id: "cn2",  text: "Which protocol provides reliable, connection-oriented communication?", options: ["TCP", "UDP", "IP", "ICMP"], correct: 0 },
      { id: "cn3",  text: "What is the default subnet mask for a Class C IP address?", options: ["255.255.255.0", "255.0.0.0", "255.255.0.0", "255.255.255.128"], correct: 0 },
      { id: "cn4",  text: "Which layer of the OSI model is responsible for routing packets?", options: ["Network Layer (Layer 3)", "Data Link Layer (Layer 2)", "Transport Layer (Layer 4)", "Session Layer (Layer 5)"], correct: 0 },
      { id: "cn5",  text: "What does DNS stand for?", options: ["Domain Name System", "Dynamic Network Service", "Distributed Name Server", "Data Network Security"], correct: 0 },
      { id: "cn6",  text: "Which protocol is used to assign IP addresses dynamically?", options: ["DHCP", "DNS", "ARP", "ICMP"], correct: 0 },
      { id: "cn7",  text: "What is the purpose of the TCP three-way handshake?", options: ["Establish a reliable connection between client and server", "Transfer data reliably", "Close a connection gracefully", "Resolve a domain name to an IP address"], correct: 0 },
      { id: "cn8",  text: "Which of the following operates at the Data Link layer?", options: ["Switch", "Router", "Hub", "Repeater"], correct: 0 },
      { id: "cn9",  text: "What does NAT (Network Address Translation) do?", options: ["Maps private IP addresses to a public IP address", "Converts domain names to IP addresses", "Encrypts network traffic", "Routes packets between different networks"], correct: 0 },
      { id: "cn10", text: "Which protocol is used to send email from a client to a mail server?", options: ["SMTP", "IMAP", "POP3", "FTP"], correct: 0 },
    ],
  },
  {
    id: "oop", label: "Object-Oriented Programming", icon: "🏗️", color: "orange",
    questions: [
      { id: "oop1",  text: "Which OOP concept bundles data and methods that operate on it into a single unit?", options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], correct: 0 },
      { id: "oop2",  text: "What is method overriding?", options: ["A subclass provides a specific implementation of a method defined in its superclass", "Defining multiple methods with the same name but different parameters", "Hiding a method from external classes", "Calling a parent class method from a child class"], correct: 0 },
      { id: "oop3",  text: "Which keyword is used to prevent a class from being subclassed in Java?", options: ["final", "static", "abstract", "sealed"], correct: 0 },
      { id: "oop4",  text: "What design pattern ensures only one instance of a class exists?", options: ["Singleton", "Factory", "Observer", "Decorator"], correct: 0 },
      { id: "oop5",  text: "What does the 'S' in SOLID principles stand for?", options: ["Single Responsibility Principle", "Substitution Principle", "Static Binding Principle", "Separation of Concerns"], correct: 0 },
      { id: "oop6",  text: "Which OOP concept allows a subclass object to be treated as a superclass object?", options: ["Polymorphism", "Encapsulation", "Abstraction", "Composition"], correct: 0 },
      { id: "oop7",  text: "What is an abstract class?", options: ["A class that cannot be instantiated and may have abstract methods", "A class with all private members", "A class that cannot be inherited", "A class with only static methods"], correct: 0 },
      { id: "oop8",  text: "Which design pattern defines a one-to-many dependency so that when one object changes state, all dependents are notified?", options: ["Observer", "Singleton", "Factory", "Strategy"], correct: 0 },
      { id: "oop9",  text: "What is the Liskov Substitution Principle?", options: ["Subtypes must be substitutable for their base types without altering correctness", "A class should have only one reason to change", "Depend on abstractions, not concretions", "Classes should be open for extension but closed for modification"], correct: 0 },
      { id: "oop10", text: "What is the difference between composition and inheritance?", options: ["Composition uses 'has-a' relationship; inheritance uses 'is-a' relationship", "Inheritance uses 'has-a' relationship; composition uses 'is-a' relationship", "They are the same concept with different names", "Composition is only used in functional programming"], correct: 0 },
    ],
  },
  {
    id: "ceh", label: "CEH — Ethical Hacking", icon: "🕵️", color: "rose",
    questions: [
      // Footprinting & Reconnaissance
      { id: "ceh1",   text: "Which phase of ethical hacking involves gathering information about the target without directly interacting with it?", options: ["Passive Reconnaissance", "Active Reconnaissance", "Scanning", "Exploitation"], correct: 0 },
      { id: "ceh2",   text: "Which tool is used to find WHOIS information about a domain?", options: ["whois", "nslookup", "traceroute", "netstat"], correct: 0 },
      { id: "ceh3",   text: "What is Google Dorking used for in footprinting?", options: ["Finding sensitive information indexed by Google", "Launching DoS attacks via search engines", "Cracking Google account passwords", "Scanning open ports on Google servers"], correct: 0 },
      { id: "ceh4",   text: "Which DNS record type maps a hostname to an IPv4 address?", options: ["A", "MX", "CNAME", "NS"], correct: 0 },
      { id: "ceh5",   text: "What does the Maltego tool primarily help with?", options: ["Visualising relationships between entities during OSINT", "Exploiting buffer overflows", "Cracking WPA2 passwords", "Scanning for open ports"], correct: 0 },
      { id: "ceh6",   text: "Which technique involves querying DNS servers to obtain a complete list of DNS records for a domain?", options: ["DNS Zone Transfer", "DNS Cache Poisoning", "DNS Tunnelling", "Reverse DNS Lookup"], correct: 0 },
      { id: "ceh7",   text: "Shodan is best described as:", options: ["A search engine for internet-connected devices", "A password cracking tool", "A web application scanner", "A network packet analyser"], correct: 0 },
      { id: "ceh8",   text: "Which social engineering technique involves creating a fabricated scenario to extract information?", options: ["Pretexting", "Phishing", "Tailgating", "Baiting"], correct: 0 },
      { id: "ceh9",   text: "What information does a traceroute command reveal?", options: ["The network path and hops between source and destination", "Open ports on a target system", "Password hashes of a target", "MAC addresses of nearby devices"], correct: 0 },
      { id: "ceh10",  text: "Which footprinting technique collects information from social media and public websites without touching the target?", options: ["OSINT (Open Source Intelligence)", "Active scanning", "Port enumeration", "Vulnerability assessment"], correct: 0 },
      // Scanning Networks
      { id: "ceh11",  text: "What tool is commonly used for network scanning and host discovery?", options: ["Nmap", "Metasploit", "Wireshark", "Burp Suite"], correct: 0 },
      { id: "ceh12",  text: "Which Nmap scan sends a SYN packet and waits for a SYN-ACK without completing the handshake?", options: ["SYN Stealth Scan (-sS)", "Full Connect Scan (-sT)", "UDP Scan (-sU)", "NULL Scan (-sN)"], correct: 0 },
      { id: "ceh13",  text: "What does an XMAS scan do?", options: ["Sets FIN, PSH, and URG flags to elicit a response from closed ports", "Sends packets with all flags set to zero", "Completes a full TCP handshake on every port", "Uses ICMP echo requests to discover hosts"], correct: 0 },
      { id: "ceh14",  text: "Which port is used by default for HTTPS?", options: ["443", "80", "8080", "22"], correct: 0 },
      { id: "ceh15",  text: "What does OS fingerprinting attempt to determine?", options: ["The operating system running on a remote host", "The passwords used by the target", "The encryption algorithm used by the target", "The physical location of the target"], correct: 0 },
      { id: "ceh16",  text: "Which scanning technique sends packets with no flags set?", options: ["NULL Scan", "FIN Scan", "XMAS Scan", "ACK Scan"], correct: 0 },
      { id: "ceh17",  text: "What is the purpose of a ping sweep?", options: ["Identify live hosts in a network range", "Crack SSH passwords", "Enumerate user accounts", "Capture network traffic"], correct: 0 },
      { id: "ceh18",  text: "Which protocol does Nmap use for host discovery by default on a local network?", options: ["ARP", "ICMP", "TCP", "UDP"], correct: 0 },
      { id: "ceh19",  text: "What is banner grabbing used for?", options: ["Identifying software versions running on open ports", "Capturing login credentials", "Intercepting encrypted traffic", "Escalating privileges"], correct: 0 },
      { id: "ceh20",  text: "Which tool is used for automated vulnerability scanning?", options: ["Nessus", "Nmap", "Wireshark", "John the Ripper"], correct: 0 },
      // Enumeration
      { id: "ceh21",  text: "Which protocol is used for NetBIOS enumeration?", options: ["SMB over port 445", "HTTP over port 80", "FTP over port 21", "SSH over port 22"], correct: 0 },
      { id: "ceh22",  text: "What does SNMP enumeration reveal?", options: ["Network device configurations and community strings", "User email addresses", "SSL certificate details", "DNS zone records"], correct: 0 },
      { id: "ceh23",  text: "Which command is used for LDAP enumeration on Windows?", options: ["ldapsearch", "nmap", "nbtscan", "enum4linux"], correct: 0 },
      { id: "ceh24",  text: "What is the default community string used in SNMPv1 for read access?", options: ["public", "private", "admin", "community"], correct: 0 },
      { id: "ceh25",  text: "Which tool is specifically designed for SMB/NetBIOS enumeration on Linux?", options: ["enum4linux", "Nikto", "SQLmap", "Aircrack-ng"], correct: 0 },
      // System Hacking
      { id: "ceh26",  text: "What are the four phases of system hacking in the CEH methodology?", options: ["Gaining Access, Escalating Privileges, Maintaining Access, Clearing Tracks", "Scanning, Enumeration, Exploitation, Reporting", "Footprinting, Scanning, Gaining Access, Reporting", "Reconnaissance, Exploitation, Lateral Movement, Exfiltration"], correct: 0 },
      { id: "ceh27",  text: "Which tool is used to extract password hashes from Windows SAM database?", options: ["Mimikatz", "John the Ripper", "Hashcat", "THC Hydra"], correct: 0 },
      { id: "ceh28",  text: "What is a Pass-the-Hash attack?", options: ["Using a captured NTLM hash to authenticate without knowing the plaintext password", "Cracking a hash using a rainbow table", "Injecting malicious hash values into a database", "Stealing cookies to hijack a session"], correct: 0 },
      { id: "ceh29",  text: "Which technique hides a malicious program inside a legitimate application?", options: ["Trojanising", "Rootkitting", "Keylogging", "Ransomware injection"], correct: 0 },
      { id: "ceh30",  text: "What is privilege escalation?", options: ["Gaining higher access rights than originally granted", "Creating a backdoor for persistent access", "Capturing keyboard input", "Hiding files from the OS"], correct: 0 },
      { id: "ceh31",  text: "Which type of rootkit operates at the kernel level?", options: ["Kernel-mode rootkit", "User-mode rootkit", "Bootloader rootkit", "Firmware rootkit"], correct: 0 },
      { id: "ceh32",  text: "What does clearing tracks in system hacking typically involve?", options: ["Deleting or modifying log files to hide activity", "Encrypting stolen data before exfiltration", "Changing user passwords after compromise", "Disabling antivirus software"], correct: 0 },
      // Malware
      { id: "ceh33",  text: "Which type of malware encrypts victim files and demands payment for decryption?", options: ["Ransomware", "Spyware", "Adware", "Rootkit"], correct: 0 },
      { id: "ceh34",  text: "What is a RAT (Remote Access Trojan)?", options: ["Malware that allows remote control of an infected machine", "A tool for scanning network ports remotely", "A type of network router used in attacks", "A script that automates password cracking"], correct: 0 },
      { id: "ceh35",  text: "Which malware type replicates itself across networks without user interaction?", options: ["Worm", "Virus", "Trojan", "Spyware"], correct: 0 },
      { id: "ceh36",  text: "What is a botnet?", options: ["A network of compromised machines controlled by an attacker", "A tool for creating secure tunnels", "A honeypot network to catch attackers", "A distributed computing platform"], correct: 0 },
      { id: "ceh37",  text: "Which analysis method runs malware in a controlled environment to observe its behaviour?", options: ["Dynamic Analysis", "Static Analysis", "Signature Analysis", "Heuristic Analysis"], correct: 0 },
      // Sniffing
      { id: "ceh38",  text: "Which tool is the most widely used packet analyser?", options: ["Wireshark", "Nmap", "Metasploit", "Burp Suite"], correct: 0 },
      { id: "ceh39",  text: "What attack technique involves sending forged ARP messages to link the attacker's MAC to a legitimate IP?", options: ["ARP Poisoning", "DNS Spoofing", "IP Spoofing", "MAC Flooding"], correct: 0 },
      { id: "ceh40",  text: "Which attack overwhelms a switch's MAC address table to make it act like a hub?", options: ["MAC Flooding", "ARP Spoofing", "VLAN Hopping", "STP Attack"], correct: 0 },
      { id: "ceh41",  text: "What is a promiscuous mode network interface used for?", options: ["Capturing all packets on the network, not just those addressed to it", "Encrypting all outbound traffic", "Blocking unauthorised network access", "Prioritising VoIP traffic"], correct: 0 },
      // Social Engineering
      { id: "ceh42",  text: "Which social engineering attack sends deceptive emails impersonating a trusted entity?", options: ["Phishing", "Vishing", "Smishing", "Tailgating"], correct: 0 },
      { id: "ceh43",  text: "What is vishing?", options: ["Voice-based phishing using phone calls", "Video-based phishing using deepfakes", "Phishing via SMS messages", "Phishing via USB drives"], correct: 0 },
      { id: "ceh44",  text: "Which social engineering technique involves physically following an authorised person into a restricted area?", options: ["Tailgating", "Pretexting", "Baiting", "Quid pro quo"], correct: 0 },
      { id: "ceh45",  text: "What is spear phishing?", options: ["A targeted phishing attack aimed at a specific individual or organisation", "A phishing attack using phone calls", "A mass phishing campaign sent to millions", "Phishing using fake Wi-Fi hotspots"], correct: 0 },
      // DoS / DDoS
      { id: "ceh46",  text: "Which DoS attack sends SYN packets without completing the three-way handshake, exhausting server resources?", options: ["SYN Flood", "UDP Flood", "Ping of Death", "Smurf Attack"], correct: 0 },
      { id: "ceh47",  text: "What is a Smurf attack?", options: ["Sending ICMP echo requests to broadcast addresses using a spoofed victim IP", "Flooding a target with SYN packets", "Exploiting a buffer overflow in a web server", "Intercepting traffic using ARP poisoning"], correct: 0 },
      { id: "ceh48",  text: "Which type of DDoS attack targets the application layer (Layer 7)?", options: ["HTTP Flood", "UDP Flood", "SYN Flood", "ICMP Flood"], correct: 0 },
      { id: "ceh49",  text: "What tool is commonly used to simulate DDoS attacks in a testing environment?", options: ["LOIC (Low Orbit Ion Cannon)", "Metasploit", "Burp Suite", "Nessus"], correct: 0 },
      // Session Hijacking
      { id: "ceh50",  text: "What is session hijacking?", options: ["Taking over a valid session between a user and a server", "Creating a fake login page to steal credentials", "Cracking session encryption keys", "Injecting malicious scripts into a web session"], correct: 0 },
      { id: "ceh51",  text: "Which attack predicts the TCP sequence number to inject packets into an existing connection?", options: ["TCP Session Hijacking", "UDP Hijacking", "SSL Stripping", "CSRF"], correct: 0 },
      { id: "ceh52",  text: "What does the HttpOnly flag on a cookie prevent?", options: ["JavaScript from accessing the cookie, mitigating XSS-based session theft", "The cookie from being sent over HTTPS", "The cookie from expiring automatically", "Cross-site request forgery attacks"], correct: 0 },
      // Evading IDS / Firewalls
      { id: "ceh53",  text: "Which technique splits malicious packets across multiple fragments to evade IDS detection?", options: ["Fragmentation", "Encryption", "Obfuscation", "Tunnelling"], correct: 0 },
      { id: "ceh54",  text: "What is a honeypot?", options: ["A decoy system designed to attract and detect attackers", "A tool for cracking WPA2 passwords", "A network device that filters malicious traffic", "A type of firewall rule"], correct: 0 },
      { id: "ceh55",  text: "Which evasion technique sends packets with a TTL low enough to expire before reaching the IDS but not the target?", options: ["TTL Manipulation", "Fragmentation", "Encryption", "Protocol Violation"], correct: 0 },
      { id: "ceh56",  text: "What is the difference between an IDS and an IPS?", options: ["IDS detects and alerts; IPS actively blocks malicious traffic", "IPS detects and alerts; IDS actively blocks", "They are identical in function", "IDS operates at Layer 7; IPS operates at Layer 3"], correct: 0 },
      // Web Server Hacking
      { id: "ceh57",  text: "Which attack exploits a web server by sending HTTP requests with malformed headers to cause a crash?", options: ["HTTP Response Splitting", "Directory Traversal", "Buffer Overflow", "Clickjacking"], correct: 0 },
      { id: "ceh58",  text: "What is directory traversal?", options: ["Accessing files outside the web root by manipulating file path inputs", "Listing all files on a web server via brute force", "Uploading malicious files to a web server", "Redirecting users to a malicious website"], correct: 0 },
      { id: "ceh59",  text: "Which tool is used for web server vulnerability scanning?", options: ["Nikto", "Wireshark", "Nmap", "Hashcat"], correct: 0 },
      { id: "ceh60",  text: "What is a web shell?", options: ["A script uploaded to a web server that allows remote command execution", "A secure terminal for managing web servers", "A browser plugin for testing web apps", "An encrypted connection to a web server"], correct: 0 },
      // Web Application Hacking
      { id: "ceh61",  text: "Which OWASP Top 10 category covers broken access control?", options: ["A01:2021", "A02:2021", "A03:2021", "A05:2021"], correct: 0 },
      { id: "ceh62",  text: "What tool is widely used for intercepting and modifying HTTP/HTTPS traffic during web app testing?", options: ["Burp Suite", "Wireshark", "Nmap", "Metasploit"], correct: 0 },
      { id: "ceh63",  text: "What is clickjacking?", options: ["Tricking a user into clicking a hidden element overlaid on a legitimate page", "Injecting malicious JavaScript into a webpage", "Stealing session cookies via XSS", "Redirecting DNS queries to a malicious server"], correct: 0 },
      { id: "ceh64",  text: "Which HTTP header prevents a page from being embedded in an iframe, mitigating clickjacking?", options: ["X-Frame-Options", "Content-Security-Policy", "X-XSS-Protection", "Strict-Transport-Security"], correct: 0 },
      { id: "ceh65",  text: "What is a CSRF (Cross-Site Request Forgery) attack?", options: ["Tricking a victim's browser into making unauthorised requests on their behalf", "Injecting scripts into a web application", "Stealing cookies via a malicious link", "Brute-forcing a web login form"], correct: 0 },
      // SQL Injection
      { id: "ceh66",  text: "Which type of SQL injection retrieves data by asking the database true/false questions?", options: ["Blind Boolean-based SQLi", "Error-based SQLi", "Union-based SQLi", "Out-of-band SQLi"], correct: 0 },
      { id: "ceh67",  text: "What tool automates SQL injection detection and exploitation?", options: ["SQLmap", "Burp Suite", "Nikto", "Nessus"], correct: 0 },
      { id: "ceh68",  text: "Which input would typically test for SQL injection vulnerability?", options: ["' OR '1'='1", "<script>alert(1)</script>", "../../../etc/passwd", "%00"], correct: 0 },
      { id: "ceh69",  text: "What is the most effective defence against SQL injection?", options: ["Parameterised queries / prepared statements", "Input length validation only", "Escaping special characters only", "Using a WAF only"], correct: 0 },
      // Wireless Hacking
      { id: "ceh70",  text: "Which tool is used to capture WPA2 handshakes for offline password cracking?", options: ["Aircrack-ng", "Wireshark", "Metasploit", "Nessus"], correct: 0 },
      { id: "ceh71",  text: "What is an Evil Twin attack?", options: ["Creating a rogue Wi-Fi access point with the same SSID as a legitimate one", "Sending deauthentication frames to disconnect clients", "Cracking WEP keys using the FMS attack", "Injecting packets into a wireless network"], correct: 0 },
      { id: "ceh72",  text: "Which wireless encryption protocol is considered most secure?", options: ["WPA3", "WPA2", "WPA", "WEP"], correct: 0 },
      { id: "ceh73",  text: "What is a deauthentication attack in wireless hacking?", options: ["Sending forged deauth frames to disconnect clients from an AP", "Cracking WPA2 pre-shared keys offline", "Impersonating a legitimate access point", "Sniffing unencrypted wireless traffic"], correct: 0 },
      { id: "ceh74",  text: "Which attack exploits the weak IV (Initialisation Vector) in WEP encryption?", options: ["FMS Attack", "PMKID Attack", "KRACK Attack", "Deauth Attack"], correct: 0 },
      // Mobile Hacking
      { id: "ceh75",  text: "What is Android rooting equivalent to on iOS?", options: ["Jailbreaking", "Side-loading", "Flashing", "Unlocking"], correct: 0 },
      { id: "ceh76",  text: "Which mobile attack intercepts communications by acting as a fake base station?", options: ["IMSI Catcher (Stingray)", "Evil Twin", "Bluejacking", "Smishing"], correct: 0 },
      { id: "ceh77",  text: "What does an APK file contain on Android?", options: ["The compiled application package for Android", "Apple iOS application binary", "A Windows executable file", "An encrypted configuration file"], correct: 0 },
      // IoT Hacking
      { id: "ceh78",  text: "Which protocol is commonly used by IoT devices for lightweight messaging?", options: ["MQTT", "HTTP", "FTP", "SNMP"], correct: 0 },
      { id: "ceh79",  text: "What is firmware analysis used for in IoT hacking?", options: ["Extracting credentials and vulnerabilities from device firmware", "Updating device firmware remotely", "Encrypting device communications", "Monitoring device power consumption"], correct: 0 },
      // Cloud Security
      { id: "ceh80",  text: "Which cloud attack involves an attacker placing a malicious VM on the same physical host as the target VM?", options: ["Side-Channel Attack", "VM Escape", "Cloud Hopper", "Hyperjacking"], correct: 0 },
      { id: "ceh81",  text: "What is a misconfigured S3 bucket vulnerability?", options: ["An AWS S3 bucket publicly accessible due to incorrect permissions", "A server-side injection via S3 file upload", "A DoS attack targeting AWS S3 endpoints", "An SSL misconfiguration on S3 HTTPS endpoints"], correct: 0 },
      // Cryptography
      { id: "ceh82",  text: "Which cryptographic attack tries all possible keys until the correct one is found?", options: ["Brute Force", "Dictionary Attack", "Birthday Attack", "Meet-in-the-Middle"], correct: 0 },
      { id: "ceh83",  text: "What is a rainbow table attack?", options: ["Using precomputed hash-to-plaintext mappings to reverse hash values", "Cracking passwords by trying common words", "Intercepting encrypted key exchanges", "Guessing passwords based on personal information"], correct: 0 },
      { id: "ceh84",  text: "Which hashing algorithm produces a 256-bit hash?", options: ["SHA-256", "MD5", "SHA-1", "CRC32"], correct: 0 },
      { id: "ceh85",  text: "What is steganography?", options: ["Hiding secret data inside ordinary files like images or audio", "Encrypting data using a symmetric key", "Encoding data in Base64 format", "Compressing data to reduce file size"], correct: 0 },
      // Exploitation & Post-Exploitation
      { id: "ceh86",  text: "Which framework provides a comprehensive library of exploits and payloads for penetration testing?", options: ["Metasploit", "Nessus", "Nmap", "Aircrack-ng"], correct: 0 },
      { id: "ceh87",  text: "What is Meterpreter in Metasploit?", options: ["An advanced payload that runs in memory and provides an interactive shell", "A network scanner module", "A password cracking plugin", "A web application fuzzer"], correct: 0 },
      { id: "ceh88",  text: "What is a buffer overflow attack?", options: ["Writing data beyond a buffer's boundary to overwrite adjacent memory and control execution", "Sending oversized HTTP requests to crash a web server", "Flooding a network buffer with traffic", "Injecting SQL into a database input buffer"], correct: 0 },
      { id: "ceh89",  text: "What is the purpose of a reverse shell?", options: ["Make the target connect back to the attacker, bypassing inbound firewall rules", "Encrypt the attacker's traffic from detection", "Crack passwords on the remote machine", "Capture all keyboard input on the target"], correct: 0 },
      { id: "ceh90",  text: "What is lateral movement in a cyberattack?", options: ["Moving from one compromised system to others within the same network", "Escalating privileges on the initial compromised machine", "Exfiltrating data to an external server", "Covering tracks by deleting log files"], correct: 0 },
      // Penetration Testing Methodology
      { id: "ceh91",  text: "What is the difference between a vulnerability scanner and a penetration test?", options: ["A scanner identifies weaknesses automatically; a pentest actively exploits them", "A pentest is automated; a scanner is manual", "They are the same thing", "A scanner is more thorough than a pentest"], correct: 0 },
      { id: "ceh92",  text: "Which pentest type gives the tester no prior knowledge of the target?", options: ["Black-box testing", "White-box testing", "Grey-box testing", "Crystal-box testing"], correct: 0 },
      { id: "ceh93",  text: "What document formally authorises a penetration tester to test a system?", options: ["Rules of Engagement / Scope of Work", "Non-Disclosure Agreement only", "Penetration Test Report", "CVE Advisory"], correct: 0 },
      { id: "ceh94",  text: "Which OWASP vulnerability involves using components with known vulnerabilities?", options: ["A06:2021", "A01:2021", "A03:2021", "A09:2021"], correct: 0 },
      { id: "ceh95",  text: "What is a pivot in penetration testing?", options: ["Using a compromised system to attack other systems in the internal network", "Escalating privileges on a compromised machine", "Hiding malware in a legitimate process", "Intercepting encrypted traffic"], correct: 0 },
      // Reporting & Ethics
      { id: "ceh96",  text: "Which phase comes last in the CEH penetration testing methodology?", options: ["Reporting", "Clearing Tracks", "Maintaining Access", "Exploitation"], correct: 0 },
      { id: "ceh97",  text: "What is a CVE (Common Vulnerabilities and Exposures)?", options: ["A publicly disclosed identifier for a known security vulnerability", "A certification for ethical hackers", "A tool for scanning web applications", "A type of exploit payload"], correct: 0 },
      { id: "ceh98",  text: "Which law in the USA governs unauthorised access to computer systems?", options: ["Computer Fraud and Abuse Act (CFAA)", "Digital Millennium Copyright Act (DMCA)", "Sarbanes-Oxley Act (SOX)", "Gramm-Leach-Bliley Act (GLBA)"], correct: 0 },
      { id: "ceh99",  text: "What distinguishes an ethical hacker from a malicious hacker?", options: ["Written authorisation and legal permission to test", "Use of different hacking tools", "Targeting only web applications", "Working remotely without physical access"], correct: 0 },
      { id: "ceh100", text: "Which CVSS score range is considered Critical severity?", options: ["9.0 – 10.0", "7.0 – 8.9", "4.0 – 6.9", "0.1 – 3.9"], correct: 0 },
    ],
  },
  {
    id: "comptia", label: "CompTIA Security+", icon: "🛡️", color: "sky",
    questions: [
      // Threats, Attacks & Vulnerabilities
      { id: "sec1",   text: "Which type of malware disguises itself as legitimate software to trick users into installing it?", options: ["Trojan Horse", "Worm", "Ransomware", "Rootkit"], correct: 0 },
      { id: "sec2",   text: "What type of attack exploits a vulnerability on the same day it is discovered, before a patch is available?", options: ["Zero-Day Attack", "Replay Attack", "Insider Threat", "Supply Chain Attack"], correct: 0 },
      { id: "sec3",   text: "Which attack sends a flood of half-open TCP connections to exhaust server resources?", options: ["SYN Flood", "UDP Flood", "Ping of Death", "Teardrop Attack"], correct: 0 },
      { id: "sec4",   text: "What is a supply chain attack?", options: ["Compromising a trusted vendor or software update to reach the final target", "Attacking the physical supply room of an organisation", "Flooding a network with traffic from multiple sources", "Stealing credentials via phishing emails"], correct: 0 },
      { id: "sec5",   text: "Which social engineering attack targets a specific high-value individual such as a CEO?", options: ["Whaling", "Phishing", "Smishing", "Vishing"], correct: 0 },
      { id: "sec6",   text: "What is a watering hole attack?", options: ["Compromising a website frequently visited by the target group", "Sending malicious emails to many recipients", "Intercepting Wi-Fi traffic at public hotspots", "Flooding a target IP with ICMP packets"], correct: 0 },
      { id: "sec7",   text: "Which attack replays previously captured authentication packets to gain unauthorised access?", options: ["Replay Attack", "Pass-the-Hash", "Credential Stuffing", "Brute Force"], correct: 0 },
      { id: "sec8",   text: "What is credential stuffing?", options: ["Using leaked username/password pairs from one breach to access other services", "Guessing passwords by trying every combination", "Injecting credentials into a web form via automation", "Cracking hashed passwords using a GPU"], correct: 0 },
      { id: "sec9",   text: "Which malware type replicates itself across a network without user interaction?", options: ["Worm", "Virus", "Trojan", "Spyware"], correct: 0 },
      { id: "sec10",  text: "What is fileless malware?", options: ["Malware that resides in memory and uses legitimate system tools, leaving no files on disk", "Malware hidden inside image files", "Malware that deletes itself after execution", "Malware that encrypts files without writing to disk"], correct: 0 },
      { id: "sec11",  text: "Which attack uses deception to manipulate people into revealing confidential information?", options: ["Social Engineering", "Brute Force", "Man-in-the-Middle", "Zero-Day Exploit"], correct: 0 },
      { id: "sec12",  text: "What is a man-in-the-browser (MitB) attack?", options: ["Malware that intercepts and modifies browser transactions in real time", "An attacker physically positioned between two communicating users", "A proxy that intercepts HTTPS traffic", "A social engineering attack via browser pop-ups"], correct: 0 },
      { id: "sec13",  text: "Which type of DoS attack uses amplification via DNS or NTP servers?", options: ["Amplification Attack", "SYN Flood", "Smurf Attack", "Fragmentation Attack"], correct: 0 },
      { id: "sec14",  text: "What is typosquatting?", options: ["Registering domain names similar to legitimate ones to deceive users", "Injecting malicious code into a trusted website", "Sending phishing emails with typos to avoid spam filters", "Cracking passwords by trying common misspellings"], correct: 0 },
      { id: "sec15",  text: "Which attack intercepts and potentially alters communication between two parties?", options: ["Man-in-the-Middle (MitM)", "Replay Attack", "DoS Attack", "SQL Injection"], correct: 0 },
      // Architecture & Design
      { id: "sec16",  text: "What is the purpose of a DMZ (Demilitarised Zone)?", options: ["Isolate public-facing servers from the internal network", "Encrypt all internal traffic", "Provide VPN access for remote users", "Monitor and log DNS queries"], correct: 0 },
      { id: "sec17",  text: "Which security model operates on the principle of 'never trust, always verify'?", options: ["Zero Trust", "Defence in Depth", "Least Privilege", "Need to Know"], correct: 0 },
      { id: "sec18",  text: "What does defence in depth mean?", options: ["Layering multiple security controls so that if one fails, others still protect the asset", "Using the strongest possible single security control", "Encrypting all data at rest and in transit", "Performing security reviews after every change"], correct: 0 },
      { id: "sec19",  text: "Which architecture separates the internal network into smaller segments to limit lateral movement?", options: ["Network Segmentation / Micro-segmentation", "Zero Trust", "Air Gapping", "DMZ"], correct: 0 },
      { id: "sec20",  text: "What is an air gap?", options: ["A physical isolation of a system from unsecured networks", "A firewall rule blocking all inbound traffic", "An encrypted VPN tunnel between two networks", "A DMZ between two firewalls"], correct: 0 },
      { id: "sec21",  text: "Which cloud model provides the highest level of control to the customer?", options: ["IaaS (Infrastructure as a Service)", "PaaS (Platform as a Service)", "SaaS (Software as a Service)", "FaaS (Function as a Service)"], correct: 0 },
      { id: "sec22",  text: "What is a jump server (bastion host)?", options: ["A hardened system used as a single access point to manage systems in a secure zone", "A redundant server that takes over if the primary fails", "A server that proxies all outbound web traffic", "A server dedicated to running vulnerability scans"], correct: 0 },
      { id: "sec23",  text: "Which concept ensures that no single person has complete control over a critical process?", options: ["Separation of Duties", "Least Privilege", "Need to Know", "Job Rotation"], correct: 0 },
      // Implementation — Cryptography & PKI
      { id: "sec24",  text: "Which encryption standard replaced DES and uses 128, 192, or 256-bit keys?", options: ["AES", "RSA", "3DES", "RC4"], correct: 0 },
      { id: "sec25",  text: "What is asymmetric encryption?", options: ["Using a public key to encrypt and a private key to decrypt", "Using the same key for both encryption and decryption", "Using two private keys — one for each party", "Encrypting with a session key derived from a password"], correct: 0 },
      { id: "sec26",  text: "Which protocol provides forward secrecy by generating a new session key for each session?", options: ["TLS with Diffie-Hellman Ephemeral (DHE/ECDHE)", "SSL 3.0", "RSA key exchange", "DES-CBC"], correct: 0 },
      { id: "sec27",  text: "What is a Certificate Authority (CA)?", options: ["A trusted entity that issues and signs digital certificates", "A server that stores encrypted passwords", "A hardware device for generating random keys", "A firewall that inspects SSL traffic"], correct: 0 },
      { id: "sec28",  text: "What does OCSP (Online Certificate Status Protocol) do?", options: ["Checks whether a digital certificate has been revoked in real time", "Issues new digital certificates to end users", "Encrypts certificate data during transmission", "Maps domain names to SSL certificate fingerprints"], correct: 0 },
      { id: "sec29",  text: "Which hashing algorithm is recommended for password storage due to its computational cost?", options: ["bcrypt", "MD5", "SHA-1", "CRC32"], correct: 0 },
      { id: "sec30",  text: "What is a digital signature used for?", options: ["Verifying the integrity and authenticity of a message", "Encrypting a message for confidentiality", "Compressing data before transmission", "Authenticating a server to a client"], correct: 0 },
      { id: "sec31",  text: "What is key escrow?", options: ["Storing a copy of encryption keys with a third party for recovery purposes", "Encrypting keys before storing them on a server", "Exchanging keys securely using asymmetric encryption", "Destroying old encryption keys after rotation"], correct: 0 },
      // Implementation — IAM
      { id: "sec32",  text: "What is multi-factor authentication (MFA)?", options: ["Using two or more verification factors from different categories", "Using two passwords for the same account", "Logging in from multiple devices simultaneously", "Requiring biometrics only"], correct: 0 },
      { id: "sec33",  text: "What are the three categories of authentication factors?", options: ["Something you know, something you have, something you are", "Password, PIN, Biometric", "Knowledge, Possession, Location", "Username, Password, Token"], correct: 0 },
      { id: "sec34",  text: "What is the principle of least privilege?", options: ["Users should have only the minimum access required to perform their job", "Administrators should have no restrictions", "All users should have equal access rights", "Privileged accounts should never be used"], correct: 0 },
      { id: "sec35",  text: "Which access control model assigns permissions based on a user's role within an organisation?", options: ["RBAC (Role-Based Access Control)", "MAC (Mandatory Access Control)", "DAC (Discretionary Access Control)", "ABAC (Attribute-Based Access Control)"], correct: 0 },
      { id: "sec36",  text: "What is federated identity management?", options: ["Allowing users to use the same identity across multiple organisations or systems", "Storing all user credentials in a centralised directory", "Requiring separate logins for each cloud service", "Issuing hardware tokens for every employee"], correct: 0 },
      { id: "sec37",  text: "What does SSO (Single Sign-On) provide?", options: ["Access to multiple applications with one set of credentials", "Automatic password rotation across all systems", "Two-factor authentication for every login", "Centralised storage of all user passwords"], correct: 0 },
      { id: "sec38",  text: "Which protocol is used for federated authentication between identity providers?", options: ["SAML (Security Assertion Markup Language)", "LDAP", "RADIUS", "Kerberos"], correct: 0 },
      { id: "sec39",  text: "What is a PAM (Privileged Access Management) solution used for?", options: ["Controlling, monitoring, and auditing privileged account access", "Encrypting all administrator passwords", "Providing MFA for standard user accounts", "Blocking privileged users from the internet"], correct: 0 },
      // Implementation — Network Security
      { id: "sec40",  text: "What does a SIEM system do?", options: ["Aggregates and analyses security events from across the network in real time", "Blocks malicious traffic at the network perimeter", "Encrypts data in transit between endpoints", "Manages user identity and access permissions"], correct: 0 },
      { id: "sec41",  text: "What is the difference between a stateful and a stateless firewall?", options: ["A stateful firewall tracks connection state; stateless evaluates each packet independently", "A stateless firewall is more secure than a stateful one", "A stateful firewall only inspects Layer 3 headers", "They are the same in modern implementations"], correct: 0 },
      { id: "sec42",  text: "Which type of IDS/IPS detects threats based on known attack signatures?", options: ["Signature-based", "Anomaly-based", "Heuristic-based", "Behaviour-based"], correct: 0 },
      { id: "sec43",  text: "What is a WAF (Web Application Firewall)?", options: ["A firewall that filters HTTP/HTTPS traffic to protect web applications", "A firewall that inspects all network packets at Layer 3", "A tool for scanning web applications for vulnerabilities", "A reverse proxy that balances web server load"], correct: 0 },
      { id: "sec44",  text: "What does a VPN provide?", options: ["An encrypted tunnel for secure communication over an untrusted network", "A dedicated private network line between two offices", "Anonymity by hiding the user's IP from all parties", "Automatic firewall rules for remote users"], correct: 0 },
      { id: "sec45",  text: "Which protocol operates at Layer 2 and is used in site-to-site VPNs?", options: ["L2TP", "IPSec", "SSL/TLS", "GRE"], correct: 0 },
      { id: "sec46",  text: "What is network access control (NAC)?", options: ["Enforcing security policy checks before allowing devices onto the network", "Controlling which websites users can access", "Blocking all external traffic at the perimeter", "Assigning IP addresses dynamically based on user role"], correct: 0 },
      { id: "sec47",  text: "What is the purpose of 802.1X?", options: ["Port-based network access control requiring authentication before LAN access", "Wireless encryption standard for WPA3", "A protocol for dynamic VLAN assignment", "A standard for network switch port mirroring"], correct: 0 },
      // Implementation — Endpoint & Application Security
      { id: "sec48",  text: "What is application whitelisting?", options: ["Allowing only approved applications to run on a system", "Blocking known malicious applications by signature", "Encrypting all application data at rest", "Logging all application activity for audit"], correct: 0 },
      { id: "sec49",  text: "Which security feature prevents a program from executing code in non-executable memory regions?", options: ["DEP (Data Execution Prevention)", "ASLR (Address Space Layout Randomisation)", "Code Signing", "Sandbox"], correct: 0 },
      { id: "sec50",  text: "What does ASLR (Address Space Layout Randomisation) do?", options: ["Randomises memory addresses to make exploitation harder", "Prevents execution of code in data segments", "Signs application binaries to verify authenticity", "Isolates applications in a restricted environment"], correct: 0 },
      { id: "sec51",  text: "What is a sandbox in security?", options: ["An isolated environment where untrusted code runs without affecting the host system", "A honeypot designed to attract attackers", "A restricted user account with no admin rights", "A network segment isolated from the internet"], correct: 0 },
      { id: "sec52",  text: "Which mobile device management concept wipes only corporate data from a personal device?", options: ["Selective Wipe / Containerisation", "Full Device Wipe", "Remote Lock", "Device Encryption"], correct: 0 },
      // Operations & Incident Response
      { id: "sec53",  text: "What are the four phases of the NIST incident response lifecycle?", options: ["Preparation, Detection & Analysis, Containment/Eradication/Recovery, Post-Incident", "Identify, Protect, Detect, Respond", "Plan, Do, Check, Act", "Triage, Investigation, Remediation, Reporting"], correct: 0 },
      { id: "sec54",  text: "What is the primary goal of the containment phase in incident response?", options: ["Stop the spread of the incident and prevent further damage", "Identify the root cause of the incident", "Restore affected systems to normal operation", "Notify law enforcement and stakeholders"], correct: 0 },
      { id: "sec55",  text: "What does chain of custody mean in digital forensics?", options: ["A documented record of who handled evidence and when", "The order in which forensic tools are applied", "Encrypting evidence before storage", "The legal chain of command for authorising a forensic investigation"], correct: 0 },
      { id: "sec56",  text: "Which type of backup only copies data changed since the last full OR incremental backup?", options: ["Incremental Backup", "Differential Backup", "Full Backup", "Mirror Backup"], correct: 0 },
      { id: "sec57",  text: "What is an RTO (Recovery Time Objective)?", options: ["The maximum acceptable time to restore a system after a disruption", "The maximum acceptable data loss measured in time", "The cost of recovering from a disaster", "The time it takes to perform a full backup"], correct: 0 },
      { id: "sec58",  text: "What is an RPO (Recovery Point Objective)?", options: ["The maximum acceptable data loss measured in time", "The maximum time to restore a system after failure", "The minimum backup frequency required by policy", "The recovery priority order for critical systems"], correct: 0 },
      { id: "sec59",  text: "What does a SOAR platform do?", options: ["Automates security incident response workflows and orchestrates tools", "Provides real-time threat intelligence feeds", "Scans networks for open ports and services", "Manages user identities and access rights"], correct: 0 },
      { id: "sec60",  text: "Which log source would you first examine to investigate a failed login attempt?", options: ["Authentication / Security event logs", "Application logs", "Network flow logs", "DNS query logs"], correct: 0 },
      { id: "sec61",  text: "What is a tabletop exercise?", options: ["A discussion-based simulation of an incident response scenario", "A live penetration test of production systems", "A physical drill where staff practice evacuating the data centre", "A red team vs blue team cyber exercise"], correct: 0 },
      // Governance, Risk & Compliance
      { id: "sec62",  text: "What does a BIA (Business Impact Analysis) identify?", options: ["Critical business functions and the impact of their disruption", "Security vulnerabilities in business applications", "The financial cost of all IT assets", "Compliance gaps against a regulatory standard"], correct: 0 },
      { id: "sec63",  text: "Which concept describes ensuring that a user cannot deny having performed an action?", options: ["Non-repudiation", "Confidentiality", "Integrity", "Availability"], correct: 0 },
      { id: "sec64",  text: "What is a risk register?", options: ["A documented list of identified risks, their likelihood, impact, and mitigation", "A log of all security incidents in an organisation", "A list of approved vendors and their risk ratings", "A record of all penetration test findings"], correct: 0 },
      { id: "sec65",  text: "Which risk response strategy involves transferring risk to a third party?", options: ["Risk Transference (e.g., insurance)", "Risk Avoidance", "Risk Mitigation", "Risk Acceptance"], correct: 0 },
      { id: "sec66",  text: "What does GDPR primarily regulate?", options: ["The processing and protection of personal data of EU residents", "The export of encryption technology", "Financial data security in banking", "Government access to citizen communications"], correct: 0 },
      { id: "sec67",  text: "Which framework provides best practices for IT service management and security?", options: ["ISO/IEC 27001", "PCI DSS", "HIPAA", "SOX"], correct: 0 },
      { id: "sec68",  text: "What is PCI DSS?", options: ["A security standard for organisations handling payment card data", "A US healthcare data protection regulation", "A framework for cloud security controls", "A UK government cybersecurity standard"], correct: 0 },
      { id: "sec69",  text: "What is the difference between a policy and a procedure?", options: ["A policy states what must be done; a procedure describes how to do it", "A procedure states what must be done; a policy describes how", "They are the same document with different names", "Policies are technical; procedures are managerial"], correct: 0 },
      { id: "sec70",  text: "Which type of backup only copies data that has changed since the last full backup?", options: ["Differential Backup", "Incremental Backup", "Full Backup", "Mirror Backup"], correct: 0 },
      // Vulnerability Management
      { id: "sec71",  text: "What is a CVE (Common Vulnerabilities and Exposures)?", options: ["A publicly disclosed identifier for a known security vulnerability", "A scoring system for vulnerability severity", "A list of approved security patches", "A database of known malware signatures"], correct: 0 },
      { id: "sec72",  text: "What does the CVSS score measure?", options: ["The severity of a security vulnerability on a scale of 0–10", "The cost to remediate a vulnerability", "The number of systems affected by a vulnerability", "The time taken to patch a vulnerability"], correct: 0 },
      { id: "sec73",  text: "What is a false positive in vulnerability scanning?", options: ["A vulnerability reported that does not actually exist", "A real vulnerability that was not detected", "An exploit that fails against a patched system", "A scan that crashes the target system"], correct: 0 },
      { id: "sec74",  text: "Which process involves applying vendor-released fixes to address known vulnerabilities?", options: ["Patch Management", "Vulnerability Assessment", "Penetration Testing", "Configuration Management"], correct: 0 },
      { id: "sec75",  text: "What is a hardened system?", options: ["A system configured to minimise its attack surface by removing unnecessary services and applying security settings", "A system with maximum processing power for security tasks", "A system physically secured in a locked data centre", "A system that has passed all penetration tests"], correct: 0 },
      // Wireless & Physical Security
      { id: "sec76",  text: "Which wireless security protocol is considered most secure for enterprise environments?", options: ["WPA3-Enterprise", "WPA2-Personal", "WPA-TKIP", "WEP"], correct: 0 },
      { id: "sec77",  text: "What is a rogue access point?", options: ["An unauthorised wireless access point installed on a network", "A misconfigured enterprise access point", "An access point with a weak password", "A wireless repeater used in a MITM attack"], correct: 0 },
      { id: "sec78",  text: "What physical security control uses two interlocked doors to prevent tailgating?", options: ["Mantrap (Airlock)", "Turnstile", "Biometric lock", "CCTV"], correct: 0 },
      { id: "sec79",  text: "What does CCTV primarily provide in terms of security controls?", options: ["Detective control — recording and monitoring activity", "Preventive control — stopping intrusions", "Corrective control — responding to incidents", "Compensating control — replacing another failed control"], correct: 0 },
      // Data Protection & Privacy
      { id: "sec80",  text: "What is data loss prevention (DLP)?", options: ["Technology that detects and prevents unauthorised transfer of sensitive data", "Encrypting all data stored on endpoint devices", "Backing up data to prevent accidental loss", "Blocking employees from accessing sensitive files"], correct: 0 },
      { id: "sec81",  text: "What is data masking?", options: ["Replacing sensitive data with realistic but fictitious values for non-production use", "Encrypting data before sending it over a network", "Hiding file metadata to prevent information leakage", "Removing all PII from a database permanently"], correct: 0 },
      { id: "sec82",  text: "Which concept ensures data is accurate, complete, and has not been tampered with?", options: ["Integrity", "Confidentiality", "Availability", "Non-repudiation"], correct: 0 },
      { id: "sec83",  text: "What is tokenisation in data security?", options: ["Replacing sensitive data with a non-sensitive placeholder (token)", "Encrypting data using a token-based algorithm", "Using hardware tokens for authentication", "Segmenting a network using VLAN tokens"], correct: 0 },
      // Cloud & Virtualisation Security
      { id: "sec84",  text: "What is the shared responsibility model in cloud security?", options: ["Security responsibilities are divided between the cloud provider and the customer", "The cloud provider is responsible for all security", "The customer is responsible for all security", "Security is shared equally between all cloud tenants"], correct: 0 },
      { id: "sec85",  text: "What is a CASB (Cloud Access Security Broker)?", options: ["A security policy enforcement point between cloud users and cloud services", "A firewall designed specifically for cloud environments", "A tool for scanning cloud infrastructure for misconfigurations", "A VPN solution for connecting to cloud services securely"], correct: 0 },
      { id: "sec86",  text: "Which attack targets the hypervisor to escape a virtual machine and access the host?", options: ["VM Escape", "Side-Channel Attack", "Container Breakout", "Hyperjacking"], correct: 0 },
      // Protocols & Ports
      { id: "sec87",  text: "Which port does SSH use by default?", options: ["22", "23", "443", "3389"], correct: 0 },
      { id: "sec88",  text: "Which protocol secures email transmission between mail servers using encryption?", options: ["SMTPS / STARTTLS", "POP3", "IMAP", "MIME"], correct: 0 },
      { id: "sec89",  text: "What does DNSSEC provide?", options: ["Cryptographic authentication of DNS responses to prevent DNS spoofing", "Encryption of DNS queries between client and server", "A secure alternative to the DNS protocol", "Rate limiting of DNS queries to prevent amplification attacks"], correct: 0 },
      { id: "sec90",  text: "Which protocol is used to securely synchronise time across network devices?", options: ["NTPsec", "SNMP", "Syslog", "LDAP"], correct: 0 },
      // Threat Intelligence & Monitoring
      { id: "sec91",  text: "What is an IOC (Indicator of Compromise)?", options: ["A piece of evidence suggesting a system has been breached", "A metric for measuring security control effectiveness", "A compliance requirement for incident documentation", "A type of malware signature in an AV database"], correct: 0 },
      { id: "sec92",  text: "What is threat hunting?", options: ["Proactively searching for hidden threats that have evaded automated detection", "Automatically blocking threats identified by a SIEM", "Running vulnerability scans to find unpatched systems", "Monitoring dark web forums for leaked credentials"], correct: 0 },
      { id: "sec93",  text: "What is the MITRE ATT&CK framework?", options: ["A knowledge base of adversary tactics and techniques based on real-world observations", "A scoring system for CVSS vulnerability severity", "A compliance framework for financial institutions", "A set of technical security controls for cloud environments"], correct: 0 },
      { id: "sec94",  text: "What does a honeypot detect?", options: ["Attackers by attracting them to a decoy system and monitoring their activity", "Malware by running suspicious files in an isolated environment", "Network intrusions by analysing traffic patterns", "Data exfiltration by monitoring outbound connections"], correct: 0 },
      { id: "sec95",  text: "Which log management concept sends logs from multiple sources to a centralised server for storage and analysis?", options: ["Centralised Logging / Syslog", "SIEM", "SOAR", "DLP"], correct: 0 },
      // Emerging & Miscellaneous
      { id: "sec96",  text: "What is a TPM (Trusted Platform Module)?", options: ["A hardware chip that stores cryptographic keys and enables secure boot", "A software module for managing TLS certificates", "A network device that enforces access control policies", "A type of hardware security token for MFA"], correct: 0 },
      { id: "sec97",  text: "What does secure boot ensure?", options: ["Only digitally signed and trusted OS components load during startup", "The hard drive is encrypted before the OS boots", "The BIOS password is verified before booting", "Network access is blocked until the OS is fully loaded"], correct: 0 },
      { id: "sec98",  text: "What is a SOC (Security Operations Centre)?", options: ["A team and facility dedicated to monitoring, detecting, and responding to security incidents", "A secure server room housing critical infrastructure", "A compliance body overseeing an organisation's security policy", "A tool for automating security incident response"], correct: 0 },
      { id: "sec99",  text: "Which security concept involves running the minimum number of services and closing unused ports?", options: ["Attack Surface Reduction / Hardening", "Least Privilege", "Defence in Depth", "Zero Trust"], correct: 0 },
      { id: "sec100", text: "What is the purpose of a penetration test in the context of Security+?", options: ["Simulate real-world attacks to identify exploitable vulnerabilities before attackers do", "Automatically patch all discovered vulnerabilities", "Replace the need for a vulnerability scanner", "Provide compliance certification for regulatory audits"], correct: 0 },
    ],
  },
  {
    id: "se", label: "Software Engineering", icon: "📐", color: "emerald",
    questions: [
      { id: "se1",  text: "Which software development model delivers working software in short iterations?", options: ["Agile", "Waterfall", "V-Model", "Spiral"], correct: 0 },
      { id: "se2",  text: "What is the purpose of unit testing?", options: ["Test individual components or functions in isolation", "Test the entire system end-to-end", "Test the integration between modules", "Test the system under load"], correct: 0 },
      { id: "se3",  text: "What does CI/CD stand for?", options: ["Continuous Integration / Continuous Deployment", "Code Integration / Code Deployment", "Continuous Inspection / Continuous Delivery", "Code Inspection / Continuous Deployment"], correct: 0 },
      { id: "se4",  text: "Which Git command creates a new branch and switches to it?", options: ["git checkout -b <branch>", "git branch <branch>", "git switch <branch>", "git merge <branch>"], correct: 0 },
      { id: "se5",  text: "What is a User Story in Agile development?", options: ["A short description of a feature from the end-user's perspective", "A detailed technical specification document", "A bug report filed by a user", "A test case written by QA"], correct: 0 },
      { id: "se6",  text: "Which design principle states that a class should have only one reason to change?", options: ["Single Responsibility Principle", "Open/Closed Principle", "Dependency Inversion", "Interface Segregation"], correct: 0 },
      { id: "se7",  text: "What is technical debt?", options: ["The cost of shortcuts taken now that must be addressed later", "Unpaid software licensing fees", "Memory leaks in production code", "Outstanding bug reports in a backlog"], correct: 0 },
      { id: "se8",  text: "In the Waterfall model, which phase comes immediately after requirements gathering?", options: ["System Design", "Implementation", "Testing", "Deployment"], correct: 0 },
      { id: "se9",  text: "What is the purpose of a code review?", options: ["Identify bugs, ensure standards, and share knowledge before merging", "Automatically test the code in CI pipeline", "Generate documentation from source code", "Deploy code to a staging environment"], correct: 0 },
      { id: "se10", text: "Which architectural pattern separates an application into three components: Model, View, Controller?", options: ["MVC", "MVP", "MVVM", "Microservices"], correct: 0 },
    ],
  },
]
